---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8

inputs:
  - name: dp-generator-api

outputs:
  - name: build

run:
  path: dp-generator-api/ci/scripts/build.sh
